### ISSUE TITLE
Grouping by Sales by Genre

### ISSUE THREAD

**Issue by shawnakumar** [knohavec/Project-1-#15]

**Comment by cccovill** [comment]
Completed pending pull, commit, push to git hub.....
# (#15) Group data by Sales by Genre
def genre_sum(x):
    return x.sum()

genre_sales_df = video_game_sales_df.groupby(["genre"]).\
            apply(lambda x: pd.Series({"Global Sales by Genre": genre_sum(x["global_sales"])}))
genre_sales_df

# (#15+) Group data by Sales by Genre - showing top 5
genre_sales_df_sorted = genre_sales_df.sort_values(by=["Global Sales by Genre",],ascending=False)
genre_sales_df_sorted.head()
