### ISSUE TITLE
API Selection and Data Retrieval

### ISSUE THREAD

**Issue by shawnakumar** [knohavec/Project-1-#7]
1. Research potential APIs from different domains.
2. Evaluate API suitability based on documentation, data availability, and ease of access.
3. Develop Python scripts for data retrieval from selected APIs.
4. Implement proper authentication and handle API rate limits.
5. Explore the Kaggle dataset on video game sales (https://www.kaggle.com/datasets/ulrikthygepedersen/video-games-sales/data).

Psuedo Code Commetns
# Import necessary libraries
# Define API endpoints and parameters
# Make HTTP request to retrieve data from the API
# Check if the request was successful
# Parse JSON response into a Pandas DataFrame

**Comment by knohavec** [comment]
done
